# -*- coding: utf-8 -*-
"""spam_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKrTbhv8LqBT1vYfWMjGexK6ed28RaJT

# Assignment 3

In this assignment you will explore text message data and create models to predict if a message is spam or not.
"""

import pandas as pd
import numpy as np

spam_data = pd.read_csv('assets/spam.csv')

spam_data['target'] = np.where(spam_data['target']=='spam',1,0)
spam_data.head(10)

from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(spam_data['text'],
                                                    spam_data['target'],
                                                    random_state=0)

"""### Question 1
What percentage of the documents in `spam_data` are spam?

*This function should return a float, the percent value (i.e. $ratio * 100$).*
"""

def answer_one():

    # YOUR CODE HERE
    spam_percent = (spam_data['target'].sum() / len(spam_data)) * 100
    return spam_percent

answer_one()



"""### Question 2

Fit the training data `X_train` using a Count Vectorizer with default parameters.

What is the longest token in the vocabulary?

*This function should return a string.*
"""

from sklearn.feature_extraction.text import CountVectorizer

def answer_two():

    # YOUR CODE HERE
    vect = CountVectorizer()
    vect.fit(X_train)
    vocab = vect.get_feature_names_out()
    longest = max(vocab, key=len)
    return longest

answer_two()



"""### Question 3

Fit and transform the training data `X_train` using a Count Vectorizer with default parameters.

Next, fit a fit a multinomial Naive Bayes classifier model with smoothing `alpha=0.1`. Find the area under the curve (AUC) score using the transformed test data.

*This function should return the AUC score as a float.*
"""

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import roc_auc_score

def answer_three():

    # YOUR CODE HERE
    vect = CountVectorizer()
    X_train_transformed = vect.fit_transform(X_train)
    X_test_transformed = vect.transform(X_test)

    clf = MultinomialNB(alpha=0.1)
    clf.fit(X_train_transformed, y_train)

    y_scores = clf.predict_proba(X_test_transformed)[:,1]
    auc = roc_auc_score(y_test, y_scores)
    return auc

answer_three()



"""### Question 4

Fit and transform the training data `X_train` using a Tfidf Vectorizer with default parameters. The transformed data will be a compressed sparse row matrix where the number of rows is the number of documents in `X_train`, the number of columns is the number of features found by the vectorizer in each document, and each value in the sparse matrix is the tf-idf value. First find the **max** tf-idf value for every feature.

What 20 features have the smallest tf-idf and what 20 have the largest tf-idf among the **max** tf-idf values?

Put these features in two series where each series is sorted by tf-idf value. The index of the series should be the feature name, and the data should be the tf-idf.

The series of 20 features with smallest tf-idfs should be sorted smallest tfidf first, the list of 20 features with largest tf-idfs should be sorted largest first. Any entries with identical tf-ids should appear in lexigraphically increasing order by their feature name in boh series. For example, if the features "a", "b", "c" had the tf-idfs 1.0, 0.5, 1.0 in the series with the largest tf-idfs, then they should occur in the returned result in the order "a", "c", "b" with values 1.0, 1.0, 0.5.

*This function should return a tuple of two series
`(smallest tf-idfs series, largest tf-idfs series)`.*
"""

from sklearn.feature_extraction.text import TfidfVectorizer

def answer_four():

    vect = TfidfVectorizer()
    X_train_tfidf = vect.fit_transform(X_train)
    max_tfidfs = X_train_tfidf.max(axis=0).toarray().flatten()
    feature_names = np.array(vect.get_feature_names_out())

    sorted_indices = np.argsort(max_tfidfs)

    smallest = pd.Series(max_tfidfs[sorted_indices[:20]], index=feature_names[sorted_indices[:20]])
    largest = pd.Series(max_tfidfs[sorted_indices[-20:]][::-1], index=feature_names[sorted_indices[-20:]][::-1])

    return (smallest, largest)

answer_four()



"""### Question 5

Fit and transform the training data `X_train` using a Tfidf Vectorizer ignoring terms that have a document frequency strictly lower than **3**.

Then fit a multinomial Naive Bayes classifier model with smoothing `alpha=0.1` and compute the area under the curve (AUC) score using the transformed test data.

*This function should return the AUC score as a float.*
"""

def answer_five():

    vect = TfidfVectorizer(min_df=3)
    X_train_tfidf = vect.fit_transform(X_train)
    X_test_tfidf = vect.transform(X_test)

    clf = MultinomialNB(alpha=0.1)
    clf.fit(X_train_tfidf, y_train)

    y_scores = clf.predict_proba(X_test_tfidf)[:,1]
    auc = roc_auc_score(y_test, y_scores)
    return auc

answer_five()



"""### Question 6

What is the average length of documents (number of characters) for not spam and spam documents?

*This function should return a tuple (average length not spam, average length spam).*
"""

def answer_six():

    spam_lengths = spam_data.loc[spam_data['target']==1, 'text'].str.len()
    notspam_lengths = spam_data.loc[spam_data['target']==0, 'text'].str.len()

    return (notspam_lengths.mean(), spam_lengths.mean())

answer_six()



"""<br>
<br>
The following function has been provided to help you combine new features into the training data:
"""

def add_feature(X, feature_to_add):
    """
    Returns sparse feature matrix with added feature.
    feature_to_add can also be a list of features.
    """
    from scipy.sparse import csr_matrix, hstack
    return hstack([X, csr_matrix(feature_to_add).T], 'csr')

"""### Question 7

Fit and transform the training data X_train using a Tfidf Vectorizer ignoring terms that have a document frequency strictly lower than **5**.

Using this document-term matrix and an additional feature, **the length of document (number of characters)**, fit a Support Vector Classification model with regularization `C=10000`. Then compute the area under the curve (AUC) score using the transformed test data.

*Hint: Since probability is set to false, use the model's `decision_function` on the test data when calculating the target scores to use in roc_auc_score*

*This function should return the AUC score as a float.*
"""

from sklearn.svm import SVC

def answer_seven():

    vect = TfidfVectorizer(min_df=5)
    X_train_tfidf = vect.fit_transform(X_train)
    X_test_tfidf = vect.transform(X_test)

    X_train_len = X_train.str.len()
    X_test_len = X_test.str.len()

    X_train_combined = add_feature(X_train_tfidf, X_train_len)
    X_test_combined = add_feature(X_test_tfidf, X_test_len)

    clf = SVC(C=10000)
    clf.fit(X_train_combined, y_train)

    y_scores = clf.decision_function(X_test_combined)
    auc = roc_auc_score(y_test, y_scores)
    return auc

answer_seven()



"""### Question 8

What is the average number of digits per document for not spam and spam documents?

*Hint: Use `\d` for digit class*

*This function should return a tuple (average # digits not spam, average # digits spam).*
"""

def answer_eight():

    digit_counts = spam_data['text'].str.count(r'\d')

    spam_digits = digit_counts[spam_data['target']==1]
    notspam_digits = digit_counts[spam_data['target']==0]

    return (notspam_digits.mean(), spam_digits.mean())

answer_eight()



"""### Question 9

Fit and transform the training data `X_train` using a Tfidf Vectorizer ignoring terms that have a document frequency strictly lower than **5** and using **word n-grams from n=1 to n=3** (unigrams, bigrams, and trigrams).

Using this document-term matrix and the following additional features:
* the length of document (number of characters)
* **number of digits per document**

fit a Logistic Regression model with regularization `C=100` and `max_iter=1000`. Then compute the area under the curve (AUC) score using the transformed test data.

*This function should return the AUC score as a float.*
"""

from sklearn.linear_model import LogisticRegression

def answer_nine():

    vect = TfidfVectorizer(min_df=5, ngram_range=(1,3))
    X_train_tfidf = vect.fit_transform(X_train)
    X_test_tfidf = vect.transform(X_test)

    lengths = X_train.str.len()
    test_lengths = X_test.str.len()

    digit_counts = X_train.str.count(r'\d')
    test_digit_counts = X_test.str.count(r'\d')

    X_train_combined = add_feature(X_train_tfidf, [lengths, digit_counts])
    X_test_combined = add_feature(X_test_tfidf, [test_lengths, test_digit_counts])

    clf = LogisticRegression(C=100, max_iter=1000)
    clf.fit(X_train_combined, y_train)

    y_scores = clf.predict_proba(X_test_combined)[:,1]
    auc = roc_auc_score(y_test, y_scores)
    return auc

answer_nine()



"""### Question 10

What is the average number of non-word characters (anything other than a letter, digit or underscore) per document for not spam and spam documents?

*Hint: Use `\w` and `\W` character classes*

*This function should return a tuple (average # non-word characters not spam, average # non-word characters spam).*
"""

def answer_ten():

    nonword_counts = spam_data['text'].str.count(r'\W')

    spam = nonword_counts[spam_data['target']==1]
    notspam = nonword_counts[spam_data['target']==0]

    return (notspam.mean(), spam.mean())

answer_ten()



"""### Question 11

Fit and transform the **first 2000 rows** of training data X_train using a Count Vectorizer ignoring terms that have a document frequency strictly lower than **5** and using **character n-grams from n=2 to n=5.**

To tell Count Vectorizer to use character n-grams pass in `analyzer='char_wb'` which creates character n-grams only from text inside word boundaries. This should make the model more robust to spelling mistakes.

Using this document-term matrix and the following additional features:
* the length of document (number of characters)
* number of digits per document
* **number of non-word characters (anything other than a letter, digit or underscore.)**

fit a Logistic Regression model with regularization C=100 and max_iter=1000. Then compute the area under the curve (AUC) score using the transformed test data.

Also **find the 10 smallest and 10 largest coefficients from the model** and return them along with the AUC score in a tuple.

The list of 10 smallest coefficients should be sorted smallest first, the list of 10 largest coefficients should be sorted largest first.

The three features that were added to the document term matrix should have the following names should they appear in the list of coefficients:
['length_of_doc', 'digit_count', 'non_word_char_count']

*This function should return a tuple `(AUC score as a float, smallest coefs list, largest coefs list)`.*
"""

def answer_eleven():

    vect = CountVectorizer(
        min_df=5,
        analyzer='char_wb',
        ngram_range=(2,5)
    )

    # Use first 2000 rows
    X_train_part = X_train[:2000]

    # Fit and transform
    X_train_vect = vect.fit_transform(X_train_part)
    X_test_vect = vect.transform(X_test)

    # Add extra features
    X_train_additional = [
        X_train_part.str.len(),
        X_train_part.apply(lambda x: sum(c.isdigit() for c in x)),
        X_train_part.str.count(r'\W')
    ]
    X_test_additional = [
        X_test.str.len(),
        X_test.apply(lambda x: sum(c.isdigit() for c in x)),
        X_test.str.count(r'\W')
    ]

    X_train_combined = add_feature(X_train_vect, X_train_additional)
    X_test_combined = add_feature(X_test_vect, X_test_additional)

    clfLG = LogisticRegression(C=100, max_iter=1000)
    clfLG.fit(X_train_combined, y_train[:2000])

    y_predicted_proba = clfLG.predict_proba(X_test_combined)[:,1]
    auc_score = roc_auc_score(y_test, y_predicted_proba)

    feature_names = np.array(
        list(vect.get_feature_names_out()) +
        ['length_of_doc', 'digit_count', 'non_word_char_count']
    )

    sorted_coef_index = clfLG.coef_[0].argsort()

    smallest_coefs = list(feature_names[sorted_coef_index[:10]])
    largest_coefs = list(feature_names[sorted_coef_index[:-11:-1]])

    return (auc_score, smallest_coefs, largest_coefs)

answer_eleven()

